pipeline:
  build:
    image: ${RUBY_VERSION}
    commands:
      - ruby -v
      - gem --version
      - bundle install --retry=2 --jobs=2
      - ./script/ci

matrix:
  RUBY_VERSION:
    - ruby:2.3.6
    - ruby:2.4.2
    - ruby:2.5.0
